<a href="https://colab.research.google.com/github/vineetkurmi/python/blob/main/basic_py_(AI_lab).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy libraries
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_squared = arr**2
print ("squared array:",arr_squared)

squared array: [ 1  4  9 16 25]


In [ ]:
#numpy libraries
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_multiplied = arr*2
print ("multiplied array;",arr_multiplied)



multiplied array; [ 2  4  6  8 10]


In [ ]:
#numpy libraries
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_added = arr +2
print ("added array;",arr_added)


added array; [3 4 5 6 7]


In [ ]:
#numpy libraries
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_substracted = arr -3
print ("substracted array;",arr_substracted)


substracted array; [-2 -1  0  1  2]


In [ ]:
from posixpath import pathsep
# CREATING A 2D NUMPY ARRAY
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print ("2d numpy array")
print (arr_2d)

2d numpy array
[[1 2 3]
 [4 5 6]]


In [ ]:
#performing operations on numpy array
arr_sum = np.sum(arr)
print ("sum of element in the array;", arr_sum)


sum of element in the array; 15


In [ ]:
# performing matrix multiplication with numpy
matrix1 = np.array([[1, 2],[2, 4]])
matrix2 = np.array([[5, 6],[7, 8]])
matrix_multiplication = np.dot(matrix1, matrix2)
print ("Matrix Product;")
print (matrix_product)

Matrix Product;
[[19 22]
 [38 44]]


In [ ]:
# performing matrix multiplication with numpy
matrix1 = np.array([[1, 2],[2, 4]])
matrix2 = np.array([[5, 6],[7, 8]])
matrix_sum = matrix1 + matrix2
print ("Matrix sum;")
print (matrix_sum)

Matrix sum;
[[ 6  8]
 [ 9 12]]


**Write a program to impliment Mean, Median and Mode.**

In [ ]:
# MEAN
import numpy as np
num = [10,20,30,40,50,60,70,80,90,100]
x = np.mean(num)
print(x)

55.0


In [ ]:
import numpy as np
num = [15,16,17,18,19,20,21,22,23]
x = np.mean(num)
print(x)

19.0


In [ ]:
print(np.__version__)

2.0.2


In [ ]:
print(np.show_config())

In [ ]:
# MEDIAN
import numpy as np
num = [10,20,30,40,50,60,70,80,90,100]
x = np.median(num)
print(x)


55.0


In [ ]:
import numpy as np
num = [15,16,17,18,19,20,21,22,23,24]
x = np.median(num)
print(x)

19.5


In [ ]:
# MODE
from scipy import stats
num = [10,20,30,40,50,60,70,80,90,100]
x = stats.mode(num)
print(x)

ModeResult(mode=np.int64(10), count=np.int64(1))


In [ ]:
from scipy import stats
num = [15,16,17,18,19,20,21,22,23]
x = stats.mode(num)
print(x)

ModeResult(mode=np.int64(15), count=np.int64(1))


In [ ]:
from scipy import stats
num =[15,16,17,18,19,20,21,22,23,24,2,5,648,89,54,65,54]
x = stats.mode(num)
print(x)

ModeResult(mode=np.int64(54), count=np.int64(2))


**Breadth First Search (BFS)**

In [ ]:
graph={
    '5' : ['3','7'],
    '3' : ['2', '4'],
    '7' : ['8'],
    '2' : [],
    '4' : ['8'],
    '8' : []
}

def bfs(visited, graph, node):
  visited.append(node)
  queue = [node]     # Initialize a queue inside the function

  while queue:    # Creating loop to visit each node
    m = queue.pop(0)
    print (m, end = " ")

    for neighbour in graph[m]:    # functions of BFS
      if neighbour not in visited:
        visited.append(neighbour)
        queue.append(neighbour)

# Driver Code
print("Following is the Breadth-First Search (BFS)")
visited = []   #List of visited nodes.
bfs(visited, graph, '5')    # Function calling

Following is the Breadth-First Search (BFS)
5 3 7 2 4 8 

In [ ]:
graph={
    '1' : ['2','3'],
    '2' : ['4'],
    '3' : ['5'],
    '4' : [],
    '5' : []
}

def bfs(visited, graph, node):
  visited.append(node)
  queue = [node]     # Initialize a queue inside the function

  while queue:    # Creating loop to visit each node
    m = queue.pop(0)
    print (m, end = " ")

    for neighbour in graph[m]:    # functions of BFS
      if neighbour not in visited:
        visited.append(neighbour)
        queue.append(neighbour)

# Driver Code
print("Following is the Breadth-First Search (BFS)")
visited = []   #List of visited nodes.
bfs(visited, graph, '1')    # Function calling

Following is the Breadth-First Search (BFS)
1 2 3 4 5 

In [ ]:
graph={
    'A' : ['B','C'],
    'B' : ['D'],
    'C' : ['E'],
    'D' : [],
    'E' : []
}

def bfs(visited, graph, node):
  visited.append(node)
  queue = [node]     # Initialize a queue inside the function

  while queue:    # Creating loop to visit each node
    m = queue.pop(0)
    print (m, end = " ")

    for neighbour in graph[m]:    # functions of BFS
      if neighbour not in visited:
        visited.append(neighbour)
        queue.append(neighbour)

# Driver Code
print("Following is the Breadth-First Search (BFS)")
visited = []   #List of visited nodes.
bfs(visited, graph, 'A')    # Function calling

Following is the Breadth-First Search (BFS)
A B C D E 

**DEPTH FIRST SEARCH (DFS)**

In [ ]:
graph={
    '5' : ['3','7'],
    '3' : ['2', '4'],
    '7' : ['8'],
    '2' : [],
    '4' : ['8'],
    '8' : []
}
visited = set()  #set to keep track of visited nodes of graph
def dfs (visited, graph, node):  #function for dfs
  if node not in visited:
    print (node)
    visited.add(node)    # Add the node to the visited set
    for neighbour in graph[node]:
      dfs(visited, graph, neighbour)

# Driver code
print("Following is the Depth-First Search")
dfs(visited, graph, '5')  # Call the dfs function

Following is the Depth-First Search
5
3
2
4
8
7


In [ ]:
graph={
    'E'  : ['C','F'],
    'C' :  ['B','D'],
    'F' :  ['H'],
    'B' :  [],
    'D' :  ['H'],
    'H' :  []
}
visited = set()  #set to keep track of visited nodes of graph
def dfs (visited, graph, node):  #function for dfs
  if node not in visited:
    print (node)
    visited.add(node)   # Add the node to the visited set
    for neighbour in graph[node]:
      dfs(visited, graph, neighbour)

# Driver code
print("Following is the Depth-First Search")
dfs(visited, graph, 'E')   # Call the dfs function

Following is the Depth-First Search
E
C
B
D
H
F


In [ ]:
graph={
    'A' : ['B','C'],
    'B' : ['E','F'],
    'C' : ['D','G'],
    'E' : [],
    'F' : ['H'],
    'D' : ['I'],
    'G' : [],
    'H' : [],
    'I' : []
}
visited = set()  #set to keep track of visited nodes of graph
def dfs (visited, graph, node):  #function for dfs
  if node not in visited:
    print (node)
    visited.add(node)   # Add the node to the visited set
    for neighbour in graph[node]:
      dfs(visited, graph, neighbour)

# Driver code
print("Following is the Depth-First Search")
dfs(visited, graph, 'A')   # Call the dfs function

Following is the Depth-First Search
A
B
E
F
H
C
D
I
G


In [ ]:
graph={
    '18' : ['19','20'],
    '19' : ['21'],
    '20' : ['22'],
    '21' : [],
    '22' : []
}
visited = set()
def dfs(visited,graph,node):
  if node not in visited:
    print (node)
    visited.add(node)
    for neighbour in graph[node]:
      dfs(visited,graph,neighbour)


print("Following is the Depth-First Search")
dfs(visited,graph,'18')

Following is the Depth-First Search
18
19
21
20
22


In [ ]:
graph={
    '18' : ['19'],
    '19' : ['20','21'],
    '20' : ['22','24'],
    '21' : ['23'],
    '22' : [],
    '23' : [],
    '24' : []
}
visited = set()  #set to keep track of visited nodes of graph
def dfs (visited, graph, node):  #function for dfs
  if node not in visited:
    print (node)
    visited.add(node)   # Add the node to the visited set
    for neighbour in graph[node]:
      dfs(visited, graph, neighbour)

# Driver code
print("Following is the Depth-First Search")
dfs(visited, graph, '18')   # Call the dfs function

Following is the Depth-First Search
18
19
20
22
24
21
23


In [ ]:
graph={
    '5' : ['3','7'],
    '3' : ['2', '4'],
    '7' : ['8'],
    '2' : [],
    '4' : ['8'],
    '8' : []
}

visited = []
goal_node = '4'
def dfs (visited, graph, node):  #function for dfs
  if node not in visited:
    print (node)
    visited.append(node)         # Add the node to the visited set
    if node == goal_node:
      print(f'\ngoal node {goal_node} found')
      return True
    for neighbour in graph[node]:
      if dfs(visited, graph, neighbour):
        return True             # Propagate the True if goal is found in a recursive call
  return False                  # Return False if the node is visited or goal not found in this branch

#Driver code
print("Following is the Depth-First Search")
dfs(visited, graph, '5')       # Call the dfs function with a valid starting node

Following is the Depth-First Search
5
3
2
4

goal node 4 found


True

In [ ]:
graph = {
    'z' : ['x','y'],
    'x' : ['u','w'],
    'y' : ['t','v'],
    'w' : [],
    'u' : [],
    't' : [],
    'v' : []
}

visited = []
goal_node = 'v'
def dfs (visited, graph, node):
  if node not in visited:
    print (node)
    visited.append(node)
    if node == goal_node:
      print(f'\ngoal node {goal_node} found')
      return True
    for neighbour in graph[node]:
      if dfs(visited, graph, neighbour):
        return True
  return False

print("Following is the Depth-First Search")
dfs(visited, graph, 'z')

Following is the Depth-First Search
z
x
u
w
y
t
v

goal node v found


True

**Alpha-Beta Pruning**

In [ ]:
tree = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F', 'G'],
    'D': [1, 2],
    'E': [3, 4],
    'F': [5, 6],
    'G': [7, 8]
}

def is_leaf(node):
    return isinstance(node, list) and all(isinstance(x, (int, float)) for x in node)

def alphabeta(node, depth, alpha, beta, maximizing):

    if is_leaf(tree[node]):
        return max(tree[node]) if maximizing else min(tree[node])

    if maximizing:
        value = float('-inf')
        for child in tree[node]:
            child_val = alphabeta(child, depth + 1, alpha, beta, False)
            value = max(value, child_val)
            alpha = max(alpha, value)
            if alpha >= beta:
                break
        return value
    else:
        value = float('inf')
        for child in tree[node]:
            child_val = alphabeta(child, depth + 1, alpha, beta, True)
            value = min(value, child_val)
            beta = min(beta, value)
            if beta <= alpha:
                break
        return value

result = alphabeta('A', 0, float('-inf'), float('inf'), True)
print("Optimal value:", result)


Optimal value: 6


**Que : Write a program to impliment tower of hanoi.**

In [ ]:
def tower_of_hanoi(n, source, auxiliary, destination):
    if n == 1:
      # Base case : Only 1 disk to move
        print(f"Move disk 1 from {source} to {destination}")
        return
    # Move n-1 disk from source to auxiliary , so they are out of the way
    tower_of_hanoi(n - 1, source, destination, auxiliary)
    # Move the nth disk from source to destination
    print(f"Move disk {n} from {source} to {destination}")
    # Move n-1 disk from auxiliary to destination
    tower_of_hanoi(n - 1, auxiliary, source, destination)

# Test the function with 3 disk
n = 3 # Number of disks
tower_of_hanoi(n, 'A', 'B', 'C')

Move disk 1 from A to C
Move disk 2 from A to B
Move disk 1 from C to B
Move disk 3 from A to C
Move disk 1 from B to A
Move disk 2 from B to C
Move disk 1 from A to C


In [ ]:
def tower_of_hanoi(n, source, auxiliary, destination):
    if n == 1:
      # Base case : Only 1 disk to move
        print(f"Move disk 1 from {source} to {destination}")
        return
    # Move n-1 disk from source to auxiliary , so they are out of the way
    tower_of_hanoi(n - 1, source, destination, auxiliary)
    # Move the nth disk from source to destination
    print(f"Move disk {n} from {source} to {destination}")
    # Move n-1 disk from auxiliary to destination
    tower_of_hanoi(n - 1, auxiliary, source, destination)

n = int(input("Enter number of disks: "))
tower_of_hanoi(n, 'A', 'B', 'C')

Enter number of disks: 3
Move disk 1 from A to C
Move disk 2 from A to B
Move disk 1 from C to B
Move disk 3 from A to C
Move disk 1 from B to A
Move disk 2 from B to C
Move disk 1 from A to C


**Que : Write a program to impliment Mean, Median, Mode and Standard Deviation.**

**Que. Write a program for Alpha-Beta Prunning**

In [ ]:
tree = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F', 'G'],
    'D': [1, 2],
    'E': [13,17],
    'F': [21,40],
    'G': [9,39]
}

def is_leaf(node):
    return isinstance(node, list) and all(isinstance(x, (int, float)) for x in node)

def alphabeta(node, depth, alpha, beta, maximizing):

    if is_leaf(tree[node]):
        return max(tree[node]) if maximizing else min(tree[node])

    if maximizing:
        value = float('-inf')
        for child in tree[node]:
            child_val = alphabeta(child, depth + 1, alpha, beta, False)
            value = max(value, child_val)
            alpha = max(alpha, value)
            if alpha >= beta:
                break
        return value
    else:
        value = float('inf')
        for child in tree[node]:
            child_val = alphabeta(child, depth + 1, alpha, beta, True)
            value = min(value, child_val)
            beta = min(beta, value)
            if beta <= alpha:
                break
        return value

result = alphabeta('A', 0, float('-inf'), float('inf'), True)
print("Optimal value:", result)

Optimal value: 39


In [ ]:
tree = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F', 'G'],
    'D': ['H', 'I'],
    'E': ['J', 'K'],
    'F': ['L', 'M'],
    'G': ['N', 'O'],
    'H': [1, 2],
    'I': [3, 4],
    'J': [5, 6],
    'K': [7, 8],
    'L': [9, 10],
    'M': [11, 12],
    'N': [13, 14],
    'O': [15, 16]
}
def is_leaf(node):
    return isinstance(node, list) and all(isinstance(x, (int, float)) for x in node)

def alphabeta(node, depth, alpha, beta, maximizing):

    if is_leaf(tree[node]):
        return max(tree[node]) if maximizing else min(tree[node])

    if maximizing:
        value = float('-inf')
        for child in tree[node]:
            child_value = alphabeta(child, depth, alpha, beta, False)
            value = max(value, child_value)
            alpha = max(alpha, value)
            if alpha >= beta:
                break
        return value
    else:
        value = float('inf')
        for child in tree[node]:
            child_value = alphabeta(child, depth, alpha, beta, True)
            value = min(value, child_value)
            beta = min(beta, value)
            if beta <= alpha:
                break
        return value

result = alphabeta('A', 0, float('-inf'), float('inf'), True)
print("Optimal value:", result)

Optimal value: 11
